---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adsbexchange-config
  namespace: default
data:
  BEASTHOST: readsb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adsbexchange
  labels:
    k8s.app: adsbexchange
spec:
  selector:
    matchLabels:
      k8s.app: adsbexchange
  template:
    metadata:
      labels:
        k8s.app: adsbexchange
    spec:
      containers:
      - name: adsbexchange
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: adsbexchange-config
        image: mikenye/adsbexchange:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 30105
---
apiVersion: v1
kind: Service
metadata:
  name: adsbexchange
  namespace: default
spec:
  ports:
  - name: mlat-client
    port: 30105
    protocol: TCP
  selector:
    k8s.app: adsbexchange
  type: ClusterIP
