---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fr24feed-config
  namespace: default
data:
  BEASTHOST: readsb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr24feed
  labels:
    k8s.app: fr24feed
spec:
  replicas: 0
  selector:
    matchLabels:
      k8s.app: fr24feed
  template:
    metadata:
      labels:
        k8s.app: fr24feed
    spec:
      containers:
      - name: fr24feed
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: fr24feed-config
        image: mikenye/fr24feed:1.0.25-3_armhf_arm64
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8754
        - containerPort: 30003
        - containerPort: 30334
---
apiVersion: v1
kind: Service
metadata:
  name: fr24feed
  namespace: default
spec:
  ports:
  - name: fr24feed-web
    port: 8754
    protocol: TCP
  - name: fr24feed-basestn-out
    port: 30003
    protocol: TCP
  - name: fr24feed-raw-out
    port: 30334
    protocol: TCP
  - name: fr24feed-mlat-client
    port: 30105
    protocol: TCP
  selector:
    k8s.app: fr24feed
  type: ClusterIP
