---
apiVersion: v1
kind: ConfigMap
metadata:
  name: piaware-config
  namespace: default
data:
  BEASTHOST: readsb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piaware
  labels:
    k8s.app: piaware
spec:
  selector:
    matchLabels:
      k8s.app: piaware
  template:
    metadata:
      labels:
        k8s.app: piaware
    spec:
      containers:
      - name: piaware
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: piaware-config
        image: mikenye/piaware:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 30001
        - containerPort: 30002
        - containerPort: 30003
        - containerPort: 30004
        - containerPort: 30005
        - containerPort: 30104
---
apiVersion: v1
kind: Service
metadata:
  name: piaware
  namespace: default
spec:
  ports:
  - name: dump1090-web
    port: 8080
    protocol: TCP
  - name: dump1090-raw-in
    port: 30001
    protocol: TCP
  - name: dump1090-raw-out
    port: 30002
    protocol: TCP
  - name: dump1090-basestn-out
    port: 30003
    protocol: TCP
  - name: dump1090-beast-in
    port: 30004
    protocol: TCP
  - name: dump1090-beast-out
    port: 30005
    protocol: TCP
  - name: dump1090-beast-in2
    port: 30104
    protocol: TCP
  - name: piaware-mlat-client
    port: 30105
    protocol: TCP
  selector:
    k8s.app: piaware
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: piaware
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: piaware
          servicePort: 8080
